image: maven:3-jdk-11

stages:
  - build
  - test
  - deploy_develop
  - deploy_staging
  - deploy_production

before_script:
  - echo "DATA VALIDATION AND DATA INGESTION"
  - echo "CI/CD Pipeline"
  - echo $CI_PROJECT_DIR

build:
  stage: build
  tags:
    - ugrad
  script: "mvn clean install"

test:
  stage: test
  tags:
    - ugrad
  script: "mvn clean test"
  artifacts:
    when: always
    reports:
      junit:
        - $CI_PROJECT_DIR/target/surefire-reports/TEST-*.xml
        - $CI_PROJECT_DIR/target/failsafe-reports/TEST-*.xml

deploy_develop:
  stage: deploy_develop
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEVELOPEMENT  --api-key=$HEROKU_API_KEY
  environment:
    name: develop
    url: https://team-3-csci-5308-developement.herokuapp.com/status
  only:
    - develop

deploy_staging:
  stage: deploy_staging
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING  --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: https://team-3-csci-5308-staging.herokuapp.com/status
  only:
    - staging

deploy_production:
  stage: deploy_production
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION  --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: https://team-3-csci-5308.herokuapp.com/status
  only:
    - main

after_script:
  - echo "Build and Test Done Successfully"
